function matches(pattern,type){return pattern==='*'||pattern===type||(pattern.endsWith('.*')&&type.startsWith(pattern.slice(0,-1)));}
function localParts(date=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);const value=type=>parts.find(part=>part.type===type)?.value;return {date:`${value('year')}-${value('month')}-${value('day')}`,time:`${value('hour')}:${value('minute')}`};}
function inQuietHours(settings,now=new Date()){const quiet=settings.quietHours;if(!quiet?.enabled)return false;const {time}=localParts(now);const start=quiet.start||'22:00';const end=quiet.end||'08:00';return start<=end?time>=start&&time<end:time>=start||time<end;}
function minutesSince(value,now=Date.now()){return value?Math.max(0,(now-new Date(value).getTime())/60_000):Infinity;}

const RULES=[
  {pattern:'task.failed',kind:'failure',importance:0.92,confidence:0.98,title:'Uma tarefa falhou',message:event=>`A tarefa ${event.taskId||'local'} falhou e pode precisar de diagnóstico.`,action:event=>({command:'inspect-task',taskId:event.taskId})},
  {pattern:'test.failed',kind:'failure',importance:0.95,confidence:0.99,title:'Testes falhando',message:event=>`Há uma falha de teste observada${event.data?.project?` em ${event.data.project}`:''}.`,action:event=>({command:'run-tests',scope:event.data?.scope})},
  {pattern:'deadline.approaching',kind:'deadline',importance:0.9,confidence:0.86,title:'Prazo em risco',message:event=>event.data?.message||'Há trabalho restante perto do prazo.',action:event=>({command:'open-planning',targetId:event.data?.targetId})},
  {pattern:'goal.stalled',kind:'stale',importance:0.7,confidence:0.8,title:'Objetivo parado',message:event=>`${event.data?.title||'Um objetivo ativo'} está sem avanço recente.`,action:event=>({command:'resume-goal',goalId:event.data?.goalId})},
  {pattern:'project.changed',kind:'project',importance:0.62,confidence:0.9,title:'Projeto alterado',message:event=>`${event.data?.project||'Um projeto'} mudou desde a última observação.`,action:event=>({command:'inspect-project',scope:event.data?.scope})},
  {pattern:'document.changed',kind:'document',importance:0.58,confidence:0.92,title:'Documento alterado',message:event=>`${event.data?.source||'Um documento'} mudou e pode precisar de reindexação.`,action:event=>({command:'index-document',source:event.data?.source})},
  {pattern:'background.failed',kind:'failure',importance:0.86,confidence:0.96,title:'Tarefa em segundo plano falhou',message:event=>event.data?.error||'Uma execução agendada falhou e preservou o diagnóstico.',action:event=>({command:'inspect-background-job',jobId:event.data?.jobId})},
  {pattern:'automation.failed',kind:'failure',importance:0.88,confidence:0.97,title:'Automação falhou',message:event=>event.data?.error||'Uma automação aprovada não concluiu.',action:event=>({command:'inspect-automation',triggerId:event.data?.triggerId})},
];

export function createProactivityEngine({store,eventBus,resources=null}){
  let automationExecutor=null; let resourceManager=resources; const thresholds={OFF:2,LOW:0.88,NORMAL:0.72,HIGH:0.58};
  function learnedRule(rule){const outcomes=store.listSuggestions({status:null,limit:500}).filter(item=>matches(rule.pattern,item.source)&&['DISMISSED','ACTED'].includes(item.status));if(outcomes.length<3)return {...rule,learning:{samples:outcomes.length,engagement:null,adjustment:0}};const acted=outcomes.filter(item=>item.status==='ACTED').length;const engagement=(acted+1)/(outcomes.length+2);const adjustment=Math.max(-0.2,Math.min(0.16,(engagement-0.5)*0.5));return {...rule,importance:Math.max(0.35,Math.min(0.99,rule.importance+adjustment)),confidence:Math.max(0.6,Math.min(0.99,rule.confidence+adjustment*0.5)),learning:{samples:outcomes.length,engagement:Number(engagement.toFixed(3)),adjustment:Number(adjustment.toFixed(3))}};}
  function assess({importance,confidence,action,sourceEventId,dedupeKey}){const settings=store.getSettings();const useful=importance>=thresholds[settings.proactivityLevel];const timely=Boolean(sourceEventId);const actionable=Boolean(action&&Object.keys(action).length);const unseen=!store.listSuggestions({status:null,limit:500}).some(item=>item.dedupeKey===dedupeKey);const confident=confidence>=(settings.proactivityLevel==='HIGH'?0.62:0.74);return {pass:useful&&timely&&actionable&&unseen&&confident,useful,timely,actionable,unseen,confident,level:settings.proactivityLevel};}
  async function consider(event){if(!event?.id||event.source==='proactivity')return null;const baseRule=RULES.find(item=>matches(item.pattern,event.type));if(!baseRule)return null;const rule=learnedRule(baseRule);const dedupeKey=`${rule.pattern}:${event.taskId||event.data?.targetId||event.data?.scope||event.id}:${localParts(new Date(event.createdAt)).date}`;const input={kind:rule.kind,title:rule.title,message:rule.message(event),importance:rule.importance,confidence:rule.confidence,reason:`Evento observado ${event.type} (${event.id}). Ajuste por feedback: ${rule.learning.adjustment}.`,source:event.type,sourceEventId:event.id,action:rule.action(event),policy:'SUGGEST',dedupeKey,expiresAt:new Date(Date.now()+7*86_400_000).toISOString()};const assessment=assess(input);if(!assessment.pass)return {suppressed:true,assessment,learning:rule.learning};const suggestion=store.putSuggestion(input);if(!suggestion.duplicate)await eventBus.publish('notification.created',{suggestionId:suggestion.id,sourceEventId:event.id,importance:suggestion.importance},{source:'proactivity'});return {...suggestion,learning:rule.learning};}
  function conditionsPass(conditions,event){if(!conditions||!Object.keys(conditions).length)return true;return Object.entries(conditions).every(([key,value])=>key==='userApproved'||event.data?.[key]===value||event[key]===value);}
  async function fireTriggers(event){if(!event?.id||event.source==='trigger-engine')return [];const fired=[];for(const trigger of store.listTriggers(true)){if(!matches(trigger.eventPattern,event.type)||!conditionsPass(trigger.conditions,event)||minutesSince(trigger.lastFiredAt)<trigger.cooldownMinutes)continue;const dedupeKey=`trigger:${trigger.id}:${event.id}`;const suggestion=store.putSuggestion({kind:'automation',title:trigger.name,message:`Regra “${trigger.name}” correspondeu ao evento ${event.type}.`,importance:0.82,confidence:0.99,reason:`Trigger ${trigger.id} baseado no evento ${event.id}.`,source:event.type,sourceEventId:event.id,action:trigger.action,policy:trigger.policy,dedupeKey});store.markTriggerFired(trigger.id);if(trigger.policy==='ACT'&&trigger.conditions?.userApproved===true&&trigger.capabilities.length&&automationExecutor){const resource=resourceManager?.decide?.({requiredRamMB:128,priority:9});if(!resource||resource.decision==='allow'){try{const result=await automationExecutor(trigger.action,{trigger,event,capabilities:trigger.capabilities});store.updateSuggestion(suggestion.id,'ACTED');await eventBus.publish('automation.dispatched',{triggerId:trigger.id,sourceEventId:event.id,resultId:result?.id||null},{source:'trigger-engine'});}catch(error){await eventBus.publish('automation.failed',{triggerId:trigger.id,sourceEventId:event.id,error:error instanceof Error?error.message:'Falha desconhecida.'},{source:'trigger-engine',level:'error'});}}}fired.push(suggestion);}return fired;}
  const unsubscribe=eventBus.subscribe('*',event=>Promise.all([consider(event),fireTriggers(event)]));
  function createTrigger(input){if(input.policy==='ACT'&&(input.userConfirmed!==true||!Array.isArray(input.capabilities)||!input.capabilities.length))throw new Error('Automação ACT exige confirmação explícita e capabilities limitadas.');return store.createTrigger(input);}
  function deliver({limit=3,now=new Date()}={}){const settings=store.getSettings();if(!settings.notificationsEnabled||settings.proactivityLevel==='OFF'||settings.focusMode||inQuietHours(settings,now))return {items:[],suppressed:true,reason:settings.focusMode?'focus-mode':inQuietHours(settings,now)?'quiet-hours':'disabled'};const {date}=localParts(now);const remaining=Math.max(0,(settings.interruptionBudget?.maxPerDay||3)-store.deliveredToday(date));const last=store.lastDelivered();if(minutesSince(last?.seenAt,now.getTime())<(settings.interruptionBudget?.minMinutesBetween||90))return {items:[],suppressed:true,reason:'interruption-cooldown'};const items=store.listSuggestions({status:'PENDING',limit:Math.min(limit,remaining)}).filter(item=>!item.expiresAt||new Date(item.expiresAt)>now);for(const item of items)store.updateSuggestion(item.id,'SEEN');return {items,suppressed:false,remaining:remaining-items.length};}
  async function scan({now=new Date(),staleDays=14}={}){const events=[];for(const goal of store.listGoals({status:['ACTIVE','BLOCKED'],limit:500})){if(goal.deadline){const days=(new Date(goal.deadline).getTime()-now.getTime())/86_400_000;if(days<=7&&goal.progress<1)events.push(await eventBus.publish('deadline.approaching',{targetId:goal.id,title:goal.title,message:`${goal.title}: ${Math.max(0,days).toFixed(1)} dia(s) restantes e ${Math.round((1-goal.progress)*100)}% ainda aberto.`},{source:'personal-scan'}));}if((now.getTime()-new Date(goal.updatedAt).getTime())/86_400_000>=staleDays)events.push(await eventBus.publish('goal.stalled',{goalId:goal.id,title:goal.title,staleDays},{source:'personal-scan'}));}for(const task of store.listTasks({status:['TODO','IN_PROGRESS','BLOCKED'],limit:1000}))if(task.deadline){const days=(new Date(task.deadline).getTime()-now.getTime())/86_400_000;if(days<=3)events.push(await eventBus.publish('deadline.approaching',{targetId:task.id,title:task.title,message:`${task.title}: prazo em ${Math.max(0,days).toFixed(1)} dia(s).`},{source:'personal-scan'}));}return events;}
  return {assess,consider,fireTriggers,createTrigger,deliver,scan,learnedRule,setAutomationExecutor(value){automationExecutor=value;},setResourceManager(value){resourceManager=value;},close(){unsubscribe?.();},health:()=>({version:'1.1.0',levels:['OFF','LOW','NORMAL','HIGH'],defaultLevel:store.getSettings().proactivityLevel,notifications:store.getSettings().notificationsEnabled,quietHours:true,interruptionBudget:true,evidenceRequired:true,precisionFirst:true,feedbackLearning:true,ruleCount:RULES.length})};
}
