const MODE_HELP = {
  GUIDE: 'Explique o caminho, dê contexto e ofereça o primeiro passo.',
  TEACH: 'Ensine com exemplo, verifique compreensão e conecte pré-requisitos.',
  CHALLENGE: 'Faça perguntas e dê apenas pistas progressivas antes da solução.',
  EXAM: 'Dê ajuda mínima, não revele a solução e avalie somente evidências da resposta.',
};

function clamp(value){return Math.max(0,Math.min(1,Number(value)||0));}
function nextIntervalDays(mastery,score){if(score<0.4)return 1;if(mastery<0.35)return 2;if(mastery<0.6)return 4;if(mastery<0.8)return 8;return 16;}
function misconception(mistakes=[]){const text=mistakes.join(' ').toLowerCase(); if(/promise|async|await/.test(text))return 'fluxo assíncrono e resolução de promises'; if(/escopo|scope|closure/.test(text))return 'escopo léxico e closures'; if(/dom|evento|listener/.test(text))return 'eventos e ciclo do DOM'; if(/tipo|type|interface/.test(text))return 'modelagem de tipos'; if(/sinal|operador|preced/.test(text))return 'precedência e operadores'; return mistakes.length?'conceito-base relacionado ao erro recorrente':null;}

export function createStudyEngine({store,memory,eventBus}){
  function recordConcept(input){if(!store.getSettings().learningHistoryEnabled)return {disabled:true};return store.upsertConcept(input);}
  async function recordAttempt({conceptId,scope='learning:global',score,result='',mistakes=[],questions=[],tutorMode=null}){
    const settings=store.getSettings(); if(!settings.learningHistoryEnabled)return {disabled:true}; const concept=store.getConcept(conceptId); if(!concept)throw new Error('Conceito não encontrado.'); const numeric=clamp(score); const evidenceWeight=questions.length?Math.min(1,questions.length/5):0.45; const nextMastery=clamp(concept.mastery*0.65+numeric*0.35*evidenceWeight+numeric*0.15); const confidence=clamp(concept.confidence*0.7+evidenceWeight*0.3); const days=nextIntervalDays(nextMastery,numeric); const nextReviewAt=settings.spacedRepetitionEnabled?new Date(Date.now()+days*86_400_000).toISOString():null; const underlying=misconception(mistakes); const updated=store.upsertConcept({...concept,mastery:nextMastery,confidence,lastReviewedAt:new Date().toISOString(),nextReviewAt,mistakes:[...concept.mistakes,...mistakes.map(item=>({at:new Date().toISOString(),value:item,underlying}))].slice(-50)}); const session=store.addStudySession({conceptId,scope,tutorMode:tutorMode||settings.tutorMode,score:numeric,result,questions,mistakes}); if(underlying)await memory.remember(`Lacuna de aprendizagem observada em ${concept.name}: ${underlying}. Evidência: ${mistakes.join('; ')}`,{kind:'error',scope,source:'TOOL',confidence:Math.min(0.9,confidence),importance:0.65,metadata:{conceptId,studySessionId:session.id}}); void eventBus?.publish('study.session.completed',{conceptId,score:numeric,mastery:updated.mastery,nextReviewAt,misconception:underlying},{source:'study-engine'}); return {concept:updated,session,misconception:underlying,nextReviewAt};
  }
  function recallQuestions({conceptId,content='',count=5}){const concept=store.getConcept(conceptId);if(!concept)throw new Error('Conceito não encontrado.');const safe=Math.max(1,Math.min(Number(count)||5,12));const details=String(content).split(/[.!?\n]/).map(item=>item.trim()).filter(item=>item.length>20).slice(0,safe);const questions=[`Explique ${concept.name} com suas próprias palavras.`,`Dê um exemplo prático de ${concept.name}.`,`Qual erro comum pode acontecer ao usar ${concept.name}?`,`Como ${concept.name} se relaciona com ${concept.dependencies[0]||'seus pré-requisitos'}?`,`Aplique ${concept.name} em um problema novo.`];for(const detail of details)questions.push(`O que significa e por que importa: “${detail.slice(0,160)}”?`);return [...new Set(questions)].slice(0,safe).map((question,index)=>({id:`q${index+1}`,question,kind:index<2?'explain':'apply',answerRevealed:false}));}
  function hint({conceptId,attempt='',level=1}){const concept=store.getConcept(conceptId);if(!concept)throw new Error('Conceito não encontrado.');const safe=Math.max(1,Math.min(Number(level)||1,3));const hints=[`Identifique primeiro o princípio central de ${concept.name}; não tente resolver tudo de uma vez.`,concept.dependencies.length?`Revise o pré-requisito “${concept.dependencies[0]}” e conecte-o ao que você já tentou.`:`Compare seu resultado com a definição e procure a primeira hipótese que não se sustenta.`,`Divida em entrada, transformação e saída; teste cada parte com um exemplo mínimo. Considere esta tentativa: ${String(attempt).slice(0,160)}`];return {conceptId,level:safe,hint:hints[safe-1],spoiler:false};}
  function planToday({scope='learning:global',limit=5,now=new Date()}={}){const settings=store.getSettings();const concepts=store.listConcepts({scope,limit:200});const due=concepts.filter(item=>item.nextReviewAt&&new Date(item.nextReviewAt)<=now);const candidates=[...due,...concepts.filter(item=>!due.some(d=>d.id===item.id))].sort((a,b)=>a.mastery-b.mastery||String(a.nextReviewAt||'z').localeCompare(String(b.nextReviewAt||'z'))).slice(0,Math.max(1,Math.min(Number(limit)||5,10)));return {scope,enabled:settings.learningHistoryEnabled,spacedRepetition:settings.spacedRepetitionEnabled,tutorMode:settings.tutorMode,due:candidates.map(item=>({concept:item,reason:item.nextReviewAt&&new Date(item.nextReviewAt)<=now?'Revisão vencida baseada em prática anterior.':item.mastery<0.5?'Domínio ainda baixo; priorizar prática e diagnóstico.':'Reforço para evitar esquecimento.',recommendedActivity:item.mastery<0.4?'TEACH':item.mastery<0.7?'CHALLENGE':'EXAM'})),evidence:{conceptIds:candidates.map(item=>item.id)}};}
  function instruction({mode=null,dontSpoil=null}={}){const settings=store.getSettings();const selected=mode||settings.tutorMode;return {mode:selected,dontSpoil:dontSpoil??settings.dontSpoil,prompt:`Modo tutor ${selected}: ${MODE_HELP[selected]||MODE_HELP.GUIDE} ${(dontSpoil??settings.dontSpoil)?'Não entregue a resposta de imediato; use pistas progressivas.':''}`};}
  return {recordConcept,recordAttempt,recallQuestions,hint,planToday,instruction,history:(scope,limit)=>store.listStudySessions(scope,limit),health:()=>({version:'1.0.0',modes:Object.keys(MODE_HELP),activeRecall:true,spacedRepetition:'opt-in',misconceptionDetection:true,dontSpoil:true})};
}
