import { defineTool } from '../tools/contracts.mjs';
import { RISK } from '../safety/policies.mjs';

export function createPersonalTools({store,work,study,search,proactivity}){
  return [
    defineTool({name:'personal.goals',description:'Lista objetivos pessoais persistentes com progresso, marcos, prazos e evidências.',risk:RISK.READ,inputSchema:{type:'object',additionalProperties:false,properties:{scope:{type:'string',maxLength:300},limit:{type:'integer',minimum:1,maximum:100}}},execute:input=>store.listGoals(input)}),
    defineTool({name:'personal.goal_create',description:'Cria um objetivo pessoal persistente; não inicia automações.',risk:RISK.WRITE,inputSchema:{type:'object',required:['title'],additionalProperties:false,properties:{title:{type:'string',minLength:2,maxLength:240},description:{type:'string',maxLength:5000},scope:{type:'string',maxLength:300},priority:{type:'integer',minimum:1,maximum:5},deadline:{type:'string',maxLength:40},status:{type:'string',enum:['IDEA','ACTIVE','PAUSED','BLOCKED']}}},execute:input=>store.createGoal(input)}),
    defineTool({name:'personal.goal_decompose',description:'Propõe marcos editáveis para um objetivo existente.',risk:RISK.WRITE,inputSchema:{type:'object',required:['goalId'],additionalProperties:false,properties:{goalId:{type:'string',minLength:8,maxLength:100},milestones:{type:'array',items:{type:'string',maxLength:240},maxItems:20}}},execute:input=>work.decompose(input.goalId,input.milestones)}),
    defineTool({name:'personal.tasks',description:'Lista tarefas pessoais por projeto ou objetivo com prioridade baseada em evidências.',risk:RISK.READ,inputSchema:{type:'object',additionalProperties:false,properties:{projectScope:{type:'string',maxLength:300},goalId:{type:'string',maxLength:100},limit:{type:'integer',minimum:1,maximum:200}}},execute:input=>work.rankTasks(input)}),
    defineTool({name:'personal.task_create',description:'Cria uma tarefa pessoal persistente vinculável a objetivo e projeto.',risk:RISK.WRITE,inputSchema:{type:'object',required:['title'],additionalProperties:false,properties:{title:{type:'string',minLength:2,maxLength:240},description:{type:'string',maxLength:5000},goalId:{type:'string',maxLength:100},projectScope:{type:'string',maxLength:300},priority:{type:'integer',minimum:1,maximum:5},deadline:{type:'string',maxLength:40},estimatedMinutes:{type:'integer',minimum:1,maximum:100000},dependencies:{type:'array',items:{type:'string',maxLength:100},maxItems:40}}},execute:input=>store.createTask(input)}),
    defineTool({name:'personal.today',description:'Monta contexto diário local com objetivos, tarefas, prazos, mudanças e foco recomendado.',risk:RISK.READ,inputSchema:{type:'object',additionalProperties:false,properties:{}},execute:()=>work.dailyContext()}),
    defineTool({name:'personal.resume',description:'Recupera objetivo, trabalho concluído, pendências, erros e próximo passo com evidências.',risk:RISK.READ,inputSchema:{type:'object',additionalProperties:false,properties:{scope:{type:'string',maxLength:300},sessionId:{type:'string',maxLength:100}}},execute:input=>work.smartResume(input)}),
    defineTool({name:'personal.search',description:'Busca unificada local em memória, projetos, documentos, tarefas, artefatos e conversas.',risk:RISK.READ,inputSchema:{type:'object',required:['query'],additionalProperties:false,properties:{query:{type:'string',minLength:2,maxLength:2000},scope:{type:'string',maxLength:300},limit:{type:'integer',minimum:1,maximum:100}}},execute:input=>search.search(input.query,input)}),
    defineTool({name:'study.plan',description:'Recomenda estudo de hoje usando domínio real, erros e revisões configuradas.',risk:RISK.READ,inputSchema:{type:'object',additionalProperties:false,properties:{scope:{type:'string',maxLength:300},limit:{type:'integer',minimum:1,maximum:10}}},execute:input=>study.planToday(input)}),
    defineTool({name:'study.recall',description:'Gera perguntas de recuperação ativa sem revelar respostas.',risk:RISK.READ,inputSchema:{type:'object',required:['conceptId'],additionalProperties:false,properties:{conceptId:{type:'string',minLength:8,maxLength:100},content:{type:'string',maxLength:12000},count:{type:'integer',minimum:1,maximum:12}}},execute:input=>study.recallQuestions(input)}),
    defineTool({name:'study.hint',description:'Fornece uma pista progressiva sem entregar a solução.',risk:RISK.READ,inputSchema:{type:'object',required:['conceptId'],additionalProperties:false,properties:{conceptId:{type:'string',minLength:8,maxLength:100},attempt:{type:'string',maxLength:4000},level:{type:'integer',minimum:1,maximum:3}}},execute:input=>study.hint(input)}),
    defineTool({name:'study.record_attempt',description:'Registra desempenho observado e atualiza domínio sem confundir exposição com aprendizado.',risk:RISK.WRITE,inputSchema:{type:'object',required:['conceptId','score'],additionalProperties:false,properties:{conceptId:{type:'string',minLength:8,maxLength:100},scope:{type:'string',maxLength:300},score:{type:'number',minimum:0,maximum:1},result:{type:'string',maxLength:4000},mistakes:{type:'array',items:{type:'string',maxLength:1000},maxItems:30},questions:{type:'array',items:{type:'string',maxLength:1000},maxItems:30},tutorMode:{type:'string',enum:['GUIDE','TEACH','CHALLENGE','EXAM']}}},execute:input=>study.recordAttempt(input)}),
    defineTool({name:'personal.notifications',description:'Lista sugestões proativas locais pendentes com fonte, razão e ação.',risk:RISK.READ,inputSchema:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:50}}},execute:input=>store.listSuggestions({status:'PENDING',limit:input.limit})}),
    defineTool({name:'automation.trigger_create',description:'Cria uma regra local SUGGEST ou ASK baseada em evento; ACT não pode ser criado autonomamente.',risk:RISK.WRITE,inputSchema:{type:'object',required:['name','eventPattern','action'],additionalProperties:false,properties:{name:{type:'string',minLength:2,maxLength:120},eventPattern:{type:'string',minLength:3,maxLength:120},conditions:{type:'object'},action:{type:'object'},policy:{type:'string',enum:['SUGGEST','ASK']},cooldownMinutes:{type:'integer',minimum:1,maximum:10080}}},execute:input=>proactivity.createTrigger(input)}),
  ];
}
