function daysUntil(value, now = Date.now()) { return value ? (new Date(value).getTime() - now) / 86_400_000 : null; }
function urgency(deadline, now) { const days = daysUntil(deadline, now); if (days == null) return 0.25; if (days <= 0) return 1; if (days <= 1) return 0.95; if (days <= 3) return 0.8; if (days <= 7) return 0.6; if (days <= 30) return 0.35; return 0.15; }
function localDate(now = new Date()) { return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(now); }

export function createPersonalWorkEngine({ store, database, continuity, eventBus, projectWorkspaces }) {
  function priorityFor(task, allTasks = [], now = Date.now()) {
    const blockedDependencies = (task.dependencies || []).filter(id => allTasks.some(candidate => candidate.id === id && candidate.status !== 'DONE')).length;
    const parts = { urgency: urgency(task.deadline, now) * 0.30, importance: ((task.priority || 3) / 5) * 0.30, dependencies: Math.min(1, blockedDependencies / 2) * -0.18, effort: task.estimatedMinutes ? Math.max(0.1, 1 - Math.min(task.estimatedMinutes, 480) / 600) * 0.12 : 0.06, blocked: task.status === 'BLOCKED' ? -0.22 : 0, active: task.status === 'IN_PROGRESS' ? 0.12 : 0 };
    const score = Math.max(0, Math.min(1, Object.values(parts).reduce((sum, value) => sum + value, 0)));
    return { score, parts, reason: task.status === 'BLOCKED' ? 'Bloqueada; resolver dependências antes de executar.' : task.deadline && daysUntil(task.deadline, now) <= 3 ? 'Prazo próximo com trabalho ainda aberto.' : task.status === 'IN_PROGRESS' ? 'Trabalho já iniciado; terminar reduz troca de contexto.' : 'Equilíbrio entre importância, prazo, dependências e esforço.' };
  }

  function rankTasks(options = {}) { const tasks = store.listTasks({ ...options, status: options.status || ['TODO','IN_PROGRESS','BLOCKED'] }); return tasks.map(task => ({ ...task, priorityEvaluation: priorityFor(task, tasks, options.now) })).sort((a,b) => b.priorityEvaluation.score-a.priorityEvaluation.score || b.priority-a.priority); }

  function defaultMilestones(goal) {
    const text = `${goal.title} ${goal.description}`.toLowerCase();
    if (/javascript|typescript/.test(text)) return ['Fundamentos e sintaxe','DOM e eventos','Assíncrono e promises','APIs e dados','Projeto prático','Avaliação e revisão'];
    if (/aprender|estudar|curso|prova/.test(text)) return ['Mapear pré-requisitos','Estudar fundamentos','Praticar com recuperação ativa','Aplicar em projeto','Avaliar domínio','Revisar lacunas'];
    if (/site|app|aplicativo|sistema|projeto/.test(text)) return ['Definir resultado e critérios','Mapear arquitetura e riscos','Construir primeira entrega verificável','Testar e corrigir','Validar com o objetivo','Documentar próximos passos'];
    return ['Definir resultado verificável','Mapear dependências','Executar primeira etapa','Revisar progresso','Concluir e validar'];
  }
  function decompose(goalId, titles = null) { const goal = store.getGoal(goalId); if (!goal) throw new Error('Objetivo não encontrado.'); const source = Array.isArray(titles) && titles.length ? titles : defaultMilestones(goal); const milestones = source.slice(0,20).map((title,index)=>({id:`m${index+1}`,title:String(title).slice(0,240),status:'TODO',progress:0,evidence:[],editable:true})); const updated=store.updateGoal(goalId,{milestones,status:goal.status==='IDEA'?'ACTIVE':goal.status}); void eventBus?.publish('goal.decomposed',{goalId,milestones:milestones.map(item=>item.title)},{source:'personal-work'}); return updated; }
  function updateGoalProgress(goalId) { const goal=store.getGoal(goalId); if(!goal) throw new Error('Objetivo não encontrado.'); const tasks=store.listTasks({goalId,limit:1000}); const milestoneValues=(goal.milestones||[]).map(item=>Number(item.progress)||(item.status==='DONE'?1:0)); const taskValues=tasks.map(item=>item.status==='DONE'?1:item.status==='IN_PROGRESS'?0.5:0); const values=[...milestoneValues,...taskValues]; const next=values.length?values.reduce((a,b)=>a+b,0)/values.length:goal.progress; return store.updateGoal(goalId,{progress:next,evidence:[...goal.evidence,{at:new Date().toISOString(),source:'criteria',completed:values.filter(value=>value>=1).length,total:values.length}].slice(-100)}); }

  function deadlineRisk(item, now = Date.now()) { const days=daysUntil(item.deadline,now); if(days==null) return {level:'NONE',confidence:1,reason:'Sem prazo definido.',estimated:true}; const remaining=item.progress!=null?1-item.progress:item.status==='DONE'?0:1; const effortDays=item.estimatedMinutes?item.estimatedMinutes/240:remaining*3; const dependencyPenalty=(item.dependencies||[]).length*0.4; const requiredDays=effortDays+dependencyPenalty; const ratio=requiredDays/Math.max(0.25,days); return {level:days<0?'OVERDUE':ratio>1?'HIGH':ratio>0.65?'MEDIUM':'LOW',confidence:item.estimatedMinutes?0.78:0.48,reason:`Estimativa: ${requiredDays.toFixed(1)} dia(s) de trabalho para ${Math.max(0,days).toFixed(1)} dia(s) disponíveis.`,estimated:true,daysRemaining:days,estimatedWorkDays:requiredDays}; }

  function projectHealth(scope) { const project=projectWorkspaces.list().find(item=>`project:${item.root}`===scope||item.root===scope); const tasks=store.listTasks({projectScope:scope,limit:500}); const agentTasks=database.listTasks(500).filter(item=>item.workingMemory?.memoryScope===scope); const events=database.listRuntimeEvents({limit:500}).filter(event=>event.data?.scope===scope||event.taskId&&agentTasks.some(task=>task.id===event.taskId)); const recentFailure=events.filter(event=>/failed|test\.failed/.test(event.type)).at(-1); const recentSuccess=events.filter(event=>/completed/.test(event.type)).at(-1); return {scope,project:project?{name:project.name,root:project.root,observedAt:project.state?.observedAt,git:project.state?.git}:null,indicators:[{name:'tests',state:recentFailure?'ATTENTION':recentSuccess?'OBSERVED_OK':'UNKNOWN',evidence:recentFailure||recentSuccess||null},{name:'openTasks',state:tasks.some(item=>item.status==='BLOCKED')?'BLOCKED':tasks.some(item=>['TODO','IN_PROGRESS'].includes(item.status))?'OPEN':'CLEAR',evidence:{open:tasks.filter(item=>['TODO','IN_PROGRESS'].includes(item.status)).length,blocked:tasks.filter(item=>item.status==='BLOCKED').length}},{name:'recentChanges',state:project?.updatedAt?'OBSERVED':'UNKNOWN',evidence:project?.updatedAt||null}],recentEvents:events.slice(-10),nextMilestone:store.listGoals({scope,status:['ACTIVE','BLOCKED'],limit:10}).flatMap(goal=>(goal.milestones||[]).filter(item=>item.status!=='DONE').slice(0,1).map(item=>({goalId:goal.id,...item})))[0]||null}; }

  async function smartResume({scope='project:.',sessionId='main'}={}) { const handoff=await continuity.build({sessionId,scope,objective:'retomar trabalho pendente'}); const scopedGoals=store.listGoals({scope,status:['ACTIVE','BLOCKED'],limit:10}); const goals=scopedGoals.length?scopedGoals:store.listGoals({status:['ACTIVE','BLOCKED'],limit:10}); const scopedTasks=rankTasks({projectScope:scope,limit:20}); const tasks=scopedTasks.length?scopedTasks:rankTasks({limit:20}); const allAgentTasks=database.listTasks(100); const scopedAgentTasks=allAgentTasks.filter(item=>item.workingMemory?.memoryScope===scope); const agentTasks=scopedAgentTasks.length?scopedAgentTasks:allAgentTasks; const last=agentTasks[0]||null; return {scope,lastObjective:handoff.previous?.objective||last?.objective||goals[0]?.title||null,completed:handoff.previous?.completed||[],pending:handoff.previous?.pending||tasks.slice(0,5).map(item=>item.title),importantFiles:handoff.previous?.artifacts||[],lastErrors:agentTasks.filter(item=>item.status==='failed').slice(0,3).map(item=>item.error),nextStep:handoff.previous?.nextSteps?.[0]||tasks[0]?.title||goals[0]?.milestones?.find(item=>item.status!=='DONE')?.title||null,evidence:{handoffId:handoff.previous?handoff.sessionId:null,taskIds:agentTasks.slice(0,5).map(item=>item.id),goalIds:goals.map(item=>item.id)}}; }

  function dailyContext(now=new Date(),{persist=false,kind='daily'}={}) { const date=localDate(now); const goals=store.listGoals({status:['ACTIVE','BLOCKED'],limit:20}); const tasks=rankTasks({limit:50,now:now.getTime()}); const deadlines=[...goals,...tasks].filter(item=>item.deadline).map(item=>({...item,risk:deadlineRisk(item,now.getTime())})).filter(item=>['OVERDUE','HIGH','MEDIUM'].includes(item.risk.level)).slice(0,10); const recent=database.listRuntimeEvents({limit:30}).slice(-12).reverse(); const snapshot={date,activeGoals:goals,pendingTasks:tasks.slice(0,12),importantDeadlines:deadlines,unfinishedWork:tasks.filter(item=>item.status==='IN_PROGRESS'||item.status==='BLOCKED').slice(0,10),recentChanges:recent,recommendedFocus:tasks[0]?{taskId:tasks[0].id,title:tasks[0].title,reason:tasks[0].priorityEvaluation.reason}:null,evidence:{goalIds:goals.map(item=>item.id),taskIds:tasks.map(item=>item.id),eventIds:recent.map(item=>item.id)}}; if(persist)store.putSnapshot({localDate:date,kind,snapshot}); return snapshot; }
  function endOfDay(now=new Date()){const date=localDate(now); const tasks=store.listTasks({limit:500}); const today=task=>String(task.completedAt||task.updatedAt).slice(0,10)===date; return {date,completed:tasks.filter(item=>item.status==='DONE'&&today(item)),unfinished:tasks.filter(item=>['TODO','IN_PROGRESS','BLOCKED'].includes(item.status)).slice(0,20),discoveries:database.listRuntimeEvents({limit:100}).filter(event=>String(event.createdAt).slice(0,10)===date&&/memory|decision|completed/.test(event.type)).slice(-10),blocked:tasks.filter(item=>item.status==='BLOCKED'),tomorrow:rankTasks({limit:10}).slice(0,5)};}
  return {priorityFor,rankTasks,decompose,updateGoalProgress,deadlineRisk,projectHealth,smartResume,dailyContext,endOfDay,health:()=>({version:'1.0.0',evidenceBasedPriority:true,editableMilestones:true,deadlineEstimates:true,smartResume:true})};
}
