'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Blocks,LoaderCircle,PlugZap,Workflow} from 'lucide-react';
import {NexoClient} from '@/lib/nexo/client';
import type{NexoCapability,NexoWorkflow}from '@/lib/nexo/types';
import{Badge}from '@/components/ui/badge';import{ScrollArea}from '@/components/ui/scroll-area';import{Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle}from '@/components/ui/sheet';import{Switch}from '@/components/ui/switch';import{Tabs,TabsContent,TabsList,TabsTrigger}from '@/components/ui/tabs';
type Props={open:boolean;token:string;onOpenChange:(open:boolean)=>void;onNotice:(message:string)=>void};
const labels:Record<string,string>={TOOL:'Tools',SKILL:'Skills',MCP:'MCP',PROVIDER:'Providers',WORKFLOW:'Workflows',CONNECTOR:'Connectors'};
export function CapabilityCenter({open,token,onOpenChange,onNotice}:Props){const[items,setItems]=useState<NexoCapability[]>([]);const[workflows,setWorkflows]=useState<NexoWorkflow[]>([]);const[loading,setLoading]=useState(false);const client=useMemo(()=>new NexoClient(token),[token]);const refresh=useCallback(async()=>{if(!token)return;setLoading(true);try{const[capabilities,flows]=await Promise.all([client.listCapabilities(),client.listWorkflows()]);setItems(capabilities);setWorkflows(flows);}catch(error){onNotice(error instanceof Error?error.message:'Falha ao carregar capacidades.');}finally{setLoading(false);}},[client,onNotice,token]);useEffect(()=>{if(open)queueMicrotask(()=>void refresh());},[open,refresh]);async function toggle(item:NexoCapability,enabled:boolean){try{const next=await client.configureCapability(item.id,enabled);setItems(current=>current.map(value=>value.id===item.id?next:value));}catch(error){onNotice(error instanceof Error?error.message:'Não foi possível alterar.');}}
 const groups=Object.keys(labels);return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-full gap-0 sm:max-w-3xl"><SheetHeader className="border-b border-border px-6 py-5"><SheetTitle className="flex items-center gap-2"><Blocks className="size-5 text-primary"/>Capacidades do Nexo</SheetTitle><SheetDescription>Descubra, diagnostique e desligue extensões. Permissões continuam subordinadas à segurança.</SheetDescription></SheetHeader>{loading?<div className="grid flex-1 place-items-center"><LoaderCircle className="animate-spin text-primary"/></div>:<Tabs defaultValue="ALL" className="min-h-0 flex-1 gap-0"><div className="overflow-x-auto border-b border-border px-5"><TabsList variant="line" className="h-12"><TabsTrigger value="ALL">Tudo</TabsTrigger>{groups.map(type=><TabsTrigger key={type} value={type}>{labels[type]}</TabsTrigger>)}</TabsList></div>{['ALL',...groups].map(type=><TabsContent key={type} value={type} className="min-h-0 flex-1"><ScrollArea className="h-[calc(100dvh-150px)] px-6 py-5"><div className="grid gap-3 md:grid-cols-2">{items.filter(item=>type==='ALL'||item.type===type).map(item=><article key={item.id} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary">{item.type==='WORKFLOW'?<Workflow className="size-4"/>:<PlugZap className="size-4"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.description}</p></div><Switch checked={item.enabled} disabled={item.trust==='BUILT_IN'&&item.type==='TOOL'} onCheckedChange={checked=>void toggle(item,checked)} aria-label={`Ativar ${item.name}`}/></div><div className="mt-3 flex flex-wrap gap-1.5"><Badge variant="outline">{item.type}</Badge><Badge variant={item.status==='AVAILABLE'?'secondary':'outline'}>{item.status}</Badge><Badge variant="outline">risco {item.risk}</Badge><Badge variant="outline">v{item.version}</Badge></div><p className="mt-3 text-[10px] text-muted-foreground">Permissões: {item.permissions.length?item.permissions.join(', '):'nenhuma adicional'} · confiança {item.trust}</p></article>)}</div>{type==='WORKFLOW'&&<p className="mt-5 text-xs text-muted-foreground">{workflows.length} workflows persistentes disponíveis.</p>}</ScrollArea></TabsContent>)}</Tabs>}</SheetContent></Sheet>}
