'use client';

import { useRef, useState } from 'react';
import { Camera, Eye, Mic, Power, ShieldX } from 'lucide-react';
import { NexoClient } from '@/lib/nexo/client';
import type { LocalAttachment, PresenceState } from '@/lib/nexo/types';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';

type Props={token:string;onCapture:(attachment:LocalAttachment)=>void;onNotice:(value:string)=>void};
async function frame(stream:MediaStream,type:'screen'|'camera'){const video=document.createElement('video');video.srcObject=stream;video.muted=true;await video.play();await new Promise(resolve=>window.setTimeout(resolve,180));const canvas=document.createElement('canvas');canvas.width=Math.min(1600,video.videoWidth||1280);canvas.height=Math.round(canvas.width*((video.videoHeight||720)/(video.videoWidth||1280)));canvas.getContext('2d')?.drawImage(video,0,0,canvas.width,canvas.height);video.pause();return{type,name:type==='screen'?'Captura de tela':'Captura da câmera',mimeType:'image/jpeg',dataUrl:canvas.toDataURL('image/jpeg',0.86)} as LocalAttachment;}
export function PresenceControls({token,onCapture,onNotice}:Props){const [presence,setPresence]=useState<PresenceState>({active:false,listening:false,viewingScreen:false,cameraActive:false,thinking:false,speaking:false,mode:'half-duplex'});const tracks=useRef<MediaStream[]>([]);const client=new NexoClient(token);
  async function capture(type:'screen'|'camera'){if(!token){onNotice('Nexo Core offline.');return;}try{const stream=type==='screen'?await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}):await navigator.mediaDevices.getUserMedia({video:true,audio:false});tracks.current.push(stream);const attachment=await frame(stream,type);onCapture(attachment);stream.getTracks().forEach(track=>track.stop());tracks.current=tracks.current.filter(item=>item!==stream);onNotice(type==='screen'?'Tela capturada sob sua autorização. Nenhum vídeo contínuo foi salvo.':'Foto da câmera capturada sob sua autorização.');}catch(error){onNotice(error instanceof Error?error.message:'Captura cancelada.');}}
  async function toggleVoice(){if(!token)return;const next=await client.updatePresence(presence.listening?{action:'update',patch:{listening:false}}:{action:'start',consent:true,voice:true});if(next.listening)speechSynthesis?.cancel();setPresence(next);}
  async function kill(){for(const stream of tracks.current)stream.getTracks().forEach(track=>track.stop());tracks.current=[];speechSynthesis?.cancel();setPresence(await client.killPresence());onNotice('Microfone, tela e câmera interrompidos.');}
  return <Popover><PopoverTrigger render={<Button size="icon-sm" variant={presence.active?'secondary':'ghost'} aria-label="Modo presença" title="Modo presença"/>}><Power /></PopoverTrigger><PopoverContent align="start" className="w-72 p-3"><div className="flex items-center justify-between"><div><p className="text-sm font-medium">Presença multimodal</p><p className="mt-1 text-[11px] text-muted-foreground">Tudo começa somente com sua ação.</p></div>{presence.active&&<Badge variant="secondary">Ativo</Badge>}</div><div className="mt-3 grid grid-cols-3 gap-2"><Button size="sm" variant={presence.listening?'secondary':'outline'} onClick={()=>void toggleVoice()}><Mic /> Ouvir</Button><Button size="sm" variant="outline" onClick={()=>void capture('screen')}><Eye /> Tela</Button><Button size="sm" variant="outline" onClick={()=>void capture('camera')}><Camera /> Câmera</Button></div>{presence.active&&<div className="mt-3 flex flex-wrap gap-1.5 text-[10px]">{presence.listening&&<Badge>Listening</Badge>}{presence.viewingScreen&&<Badge>Viewing Screen</Badge>}{presence.cameraActive&&<Badge>Camera Active</Badge>}{presence.thinking&&<Badge>Thinking</Badge>}{presence.speaking&&<Badge>Speaking</Badge>}</div>}<Button className="mt-3 w-full" size="sm" variant="destructive" onClick={()=>void kill()}><ShieldX /> Interromper tudo</Button><p className="mt-3 text-[10px] leading-4 text-muted-foreground">Capturas são pontuais. Presença não salva automaticamente tudo que você vê ou fala.</p></PopoverContent></Popover>;
}
