import { join } from 'node:path';
import { createArtifactStore } from '../artifacts/store.mjs';
import { createAudioProvider } from '../audio/http-provider.mjs';
import { createAudioRuntime } from '../audio/runtime.mjs';
import { createBackgroundScheduler } from '../background/scheduler.mjs';
import { createBrowserAgent, findBrowser } from '../browser/browser-agent.mjs';
import { createPlaywrightBrowserProvider } from '../browser/playwright-provider.mjs';
import { createCodingAgent } from '../coding/coding-agent.mjs';
import { createAgentConfig } from '../config.mjs';
import { createContextEngine } from '../context/context-engine.mjs';
import { createRag } from '../context/rag.mjs';
import { createRepositoryIntelligence } from '../context/repository-map.mjs';
import { createEventBus } from '../events/event-bus.mjs';
import { createDebuggingEngine } from '../debugging/engine.mjs';
import { createGoalEngine } from '../goals/engine.mjs';
import { createA1111ImageProvider } from '../image/a1111-provider.mjs';
import { createImageRuntime } from '../image/runtime.mjs';
import { createComplexityEstimator } from '../intelligence/complexity.mjs';
import { createResponseIntelligence } from '../intelligence/response.mjs';
import { createMcpManager } from '../mcp/client.mjs';
import { createDatabase } from '../memory/database.mjs';
import { createMemoryGate } from '../memory/gate.mjs';
import { createLongTermMemory } from '../memory/long-term.mjs';
import { createSemanticEmbeddings } from '../memory/semantic-embeddings.mjs';
import { createMediaQueue } from '../media/queue.mjs';
import { createOllamaClient } from '../models/ollama.mjs';
import { createModelProfiles } from '../models/profiles.mjs';
import { createModelRouter } from '../models/router.mjs';
import { createLogger } from '../observability/logger.mjs';
import { createAgentLoop } from '../orchestrator/agent-loop.mjs';
import { createCritic } from '../orchestrator/critic.mjs';
import { createEvaluator } from '../orchestrator/evaluator.mjs';
import { createExecutor } from '../orchestrator/executor.mjs';
import { createPlanner } from '../orchestrator/planner.mjs';
import { createPersonalityEngine } from '../personality/engine.mjs';
import { createResearchAgent } from '../research/research-agent.mjs';
import { createResourceManager } from '../resources/manager.mjs';
import { createNexoRuntime } from '../runtime/nexo-runtime.mjs';
import { createPermissionManager } from '../safety/permissions.mjs';
import { createCapabilityManager } from '../safety/capabilities.mjs';
import { createSandbox } from '../safety/sandbox.mjs';
import { createSkillEngine } from '../skills/skill-engine.mjs';
import { createMultiAgentCoordinator } from '../specialists/coordinator.mjs';
import { createSpecialistRegistry } from '../specialists/registry.mjs';
import { createFilesystemTools } from '../tools/filesystem.mjs';
import { createGitTools } from '../tools/git.mjs';
import { createProjectTools } from '../tools/project.mjs';
import { createToolRegistry } from '../tools/registry.mjs';
import { createTerminalTools } from '../tools/terminal.mjs';
import { createOllamaVisionProvider } from '../vision/ollama-provider.mjs';
import { createVisionRuntime } from '../vision/runtime.mjs';
import { createVideoProvider } from '../video/http-provider.mjs';
import { createVideoRuntime } from '../video/runtime.mjs';
import { createProjectWorkspaceManager } from '../workspace/project-workspace.mjs';
import { createCheckpointManager } from './checkpoints.mjs';
import { createTaskGraph } from './task-graph.mjs';

export function createNexoCore(overrides = {}) {
  const config = createAgentConfig(overrides); const database = createDatabase(config.dataDir); const logger = createLogger(config.dataDir); const eventBus = createEventBus({ database, logger });
  const filesystem = createFilesystemTools(config.workspace); const sandbox = createSandbox({ workspace: config.workspace, timeoutMs: config.limits.commandTimeoutMs, maxOutput: config.limits.maxToolOutput });
  const repository = createRepositoryIntelligence({ workspace: config.workspace, database }); const research = createResearchAgent(overrides.research || {}); const skills = createSkillEngine({ roots: [join(config.projectRoot, 'skills'), join(config.dataDir, 'skills')], database });
  const specialists = createSpecialistRegistry(); const coordinator = createMultiAgentCoordinator({ database, eventBus, maxParallel: 4 }); const resolvedBrowserPath = overrides.browserPath === undefined ? findBrowser() : overrides.browserPath; const browser = createBrowserAgent({ workspace: config.workspace, database, research, browserPath: resolvedBrowserPath }); const browserAutomation = createPlaywrightBrowserProvider({ workspace: config.workspace, database, research, browserPath: resolvedBrowserPath }); const coding = createCodingAgent({ repository, sandbox }); const debugging = createDebuggingEngine({ database }); const goals = createGoalEngine(); const capabilities = createCapabilityManager(database);
  const projectWorkspaces = createProjectWorkspaceManager({ workspace: config.workspace, database, repository, sandbox }); const mcp = createMcpManager({ workspace: config.workspace, configPath: overrides.mcpConfigPath || join(config.dataDir, 'mcp-servers.json') }); const scheduler = createBackgroundScheduler({ database, eventBus, tickMs: overrides.schedulerTickMs, autoStart: overrides.autoStartScheduler !== false });
  const registry = createToolRegistry([...filesystem.definitions, ...createProjectTools(filesystem), ...createGitTools(sandbox), ...createTerminalTools(sandbox), ...repository.tools, ...projectWorkspaces.definitions, ...research.definitions, ...browser.definitions, ...browserAutomation.definitions, ...coding.definitions, ...debugging.definitions, ...skills.definitions, ...mcp.definitions, ...scheduler.definitions, ...coordinator.definitions]);
  const estimator = createComplexityEstimator(); const embeddings = createSemanticEmbeddings({ ollamaUrl: config.ollamaUrl, model: config.embeddingModel, fetchImpl: overrides.fetchImpl }); const memoryGate = createMemoryGate(database); const permissionManager = createPermissionManager(database); const memory = createLongTermMemory(database, embeddings, memoryGate); const personality = createPersonalityEngine(database); const rag = createRag({ database, workspace: config.workspace, filesystem, embeddings });
  const profiles = createModelProfiles({ config, database, fetchImpl: overrides.fetchImpl }); const resources = createResourceManager({ profiles }); const router = createModelRouter(config, database, estimator, profiles, resources); const ollama = createOllamaClient(config); const responseIntelligence = createResponseIntelligence({ personality }); const artifacts = createArtifactStore({ dataDir: config.dataDir, database });
  const vision = createVisionRuntime({ provider: createOllamaVisionProvider({ config, filesystem, fetchImpl: overrides.fetchImpl }), enabled: config.featureFlags.vision }); const image = createImageRuntime({ provider: createA1111ImageProvider({ baseUrl: config.imageProviderUrl, fetchImpl: overrides.fetchImpl }), artifacts, vision, enabled: config.featureFlags.imageGeneration, autoRegeneration: config.featureFlags.autoRegeneration });
  const audioProvider = createAudioProvider({ sttUrl: config.speechToTextUrl, ttsUrl: config.textToSpeechUrl, fetchImpl: overrides.fetchImpl }); const audio = createAudioRuntime({ provider: audioProvider, artifacts, enabled: Boolean(config.speechToTextUrl || config.textToSpeechUrl) }); const video = createVideoRuntime({ provider: createVideoProvider({ baseUrl: config.videoProviderUrl, fetchImpl: overrides.fetchImpl }), artifacts, enabled: config.featureFlags.videoGeneration });
  const mediaQueue = createMediaQueue({ database, resourceManager: resources, handlers: { image: { resources: { requiredRamMB: 2500, requiredVramMB: 3500 }, run: (input, options) => image.generate(input, options) }, video: { resources: { requiredRamMB: 6000, requiredVramMB: 6000 }, run: (input, options) => video.generate(input, options) }, tts: { resources: { requiredRamMB: 500 }, run: (input, options) => audio.synthesize(input, options) } } }); void profiles.refresh().catch(() => undefined);
  const contextEngine = createContextEngine({ memory, rag, repository, skills, router, maxTokens: config.limits.contextTokens || 6000 }); const planner = createPlanner({ ollama, router, specialists }); const executor = createExecutor({ registry, database, logger, maxOutput: config.limits.maxToolOutput }); const evaluator = createEvaluator(); const critic = createCritic({ ollama, router }); const taskGraph = createTaskGraph(database); const checkpoints = createCheckpointManager(database, taskGraph);
  const loop = createAgentLoop({ config, database, registry, permissionManager, planner, executor, evaluator, critic, memory, rag, logger, taskGraph, checkpoints, contextEngine, eventBus, goalEngine: goals, specialistRegistry: specialists, capabilityManager: capabilities }); const runtime = createNexoRuntime({ config, memory, rag, ollama, research, loop, personality, router, estimator, responseIntelligence, eventBus }); scheduler.setExecutor(objective => loop.enqueueTask(objective)); coordinator.setLoop(loop); const resumedTasks = overrides.autoResume === false ? 0 : loop.resumeInterrupted();
  return { version: '5.0.0', config, database, registry, goals, capabilities, debugging, projectWorkspaces, estimator, responseIntelligence, embeddings, memoryGate, memory, rag, router, profiles, resources, artifacts, vision, image, audio, video, mediaQueue, loop, runtime, personality, repository, contextEngine, taskGraph, checkpoints, research, browser, browserAutomation, coding, skills, specialists, coordinator, mcp, scheduler, eventBus, critic,
    health() { const tasks = database.listTasks(100); return { runtime: 'Nexo Core', version: '5.0.0', persistent: true, database: 'SQLite local', tools: registry.describe(), models: router.capabilities(), taskGraph: true, checkpoints: true, contextEngine: true, repositoryIntelligence: true, critic: critic.health(), resumedTasks, capabilities: { goals: goals.health(), capabilityTokens: capabilities.health(), debugging: debugging.health(), workspace: projectWorkspaces.health(), intelligence: estimator.health(), response: responseIntelligence.health(), runtime: runtime.health(), personality: personality.health(), embeddings: embeddings.health(), memory: memory.health(), rag: rag.health(), profiles: profiles.health(), resources: resources.health(), artifacts: artifacts.health(), vision: vision.health(), image: image.health(), audio: audio.health(), video: video.health(), mediaQueue: mediaQueue.health(), safety: { processIsolation: 'allowlisted-spawn', osIsolation: false, shell: false }, research: research.health(), browser: { legacy: browser.health(), automation: browserAutomation.health() }, coding: coding.health(), skills: skills.health(), specialists: specialists.list(), multiAgent: coordinator.health(), mcp: mcp.health(), background: scheduler.health(), events: eventBus.health(), visualVerification: true, featureFlags: config.featureFlags }, tasks: { total: tasks.length, running: tasks.filter(task => ['planning', 'running', 'awaiting_approval', 'paused'].includes(task.status)).length }, limits: config.limits }; },
    close() { scheduler.close(); void browserAutomation.closeAll(); void mcp.close(); database.db.close(); },
  };
}
